version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DOCKER_RUNNING=True
      - POSTGRES_DB=shoppingcart
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "5173:5173"

  db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: shoppingcart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - cart_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  cart_postgres_data:
